// @vitest-environment jsdom
/**
 * MapLibre/OPFS seam: the pmtiles protocol serves pack archives from OPFS
 * when a full corridor pack is bound, and falls back to the network
 * protocol for every other URL. Uses the committed tiny-pack fixture
 * (web/src/map/__fixtures__/tiny-pack.pmtiles, generated by
 * web/scripts/build-corridor-pack.py).
 */
import { afterEach, describe, expect, it, vi } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  bindCorridorPackToProtocol,
  registerPmtilesProtocol,
  unbindCorridorPackFromProtocol,
} from "./pmtiles-protocol.ts";
import { TERRAIN_OFFLINE_FILES } from "../offline/corridor-policy.ts";

const FIXTURE_PATH = resolve(
  process.cwd(),
  "src/map/__fixtures__/tiny-pack.pmtiles",
);
const FIXTURE_BYTES = readFileSync(FIXTURE_PATH);

const { addProtocolMock } = vi.hoisted(() => ({ addProtocolMock: vi.fn() }));

vi.mock("maplibre-gl", () => ({
  default: { addProtocol: addProtocolMock },
}));

type Handler = (
  params: { url: string; type?: string },
  abortController: AbortController,
) => Promise<{ data: unknown }>;

let handler: Handler;

function packBlob(): Blob {
  return new Blob([FIXTURE_BYTES]);
}

const PACK_BASE = "/packages/qaarsut-kullorsuaq";

function tileUrl(path: string, z: number, x: number, y: number): string {
  return `pmtiles://${PACK_BASE}/${path}/${z}/${x}/${y}.webp`;
}

function tilejsonUrl(path: string): string {
  return `pmtiles://${PACK_BASE}/${path}`;
}

afterEach(() => {
  unbindCorridorPackFromProtocol();
  vi.unstubAllGlobals();
});

describe("pmtiles protocol offline seam", () => {
  it("registers once and captures the MapLibre protocol handler", () => {
    registerPmtilesProtocol();
    registerPmtilesProtocol();
    expect(addProtocolMock).toHaveBeenCalledTimes(1);
    handler = addProtocolMock.mock.calls[0]![1] as Handler;
    expect(handler).toBeTypeOf("function");
  });

  it("serves pack tiles from OPFS after bind, before any network", async () => {
    registerPmtilesProtocol();
    handler = addProtocolMock.mock.calls[0]![1] as Handler;

    await bindCorridorPackToProtocol(async (path) =>
      TERRAIN_OFFLINE_FILES.includes(path as (typeof TERRAIN_OFFLINE_FILES)[number])
        ? packBlob()
        : null,
    );

    const abort = new AbortController();
    const tile = await handler(
      { url: tileUrl("land-relief.pmtiles", 3, 1, 1) },
      abort,
    );
    const bytes = tile.data as Uint8Array;
    expect(new TextDecoder().decode(bytes)).toBe("tile-abc");

    const other = await handler(
      { url: tileUrl("coastline-land/land.pmtiles", 3, 2, 1) },
      abort,
    );
    expect(new TextDecoder().decode(other.data as Uint8Array)).toBe(
      "tile-xyz",
    );

    // Tilejson request for the same archive resolves locally too.
    const json = await handler(
      { url: tilejsonUrl("land-relief.pmtiles"), type: "json" },
      abort,
    );
    const tilejson = json.data as {
      tiles: string[];
      minzoom: number;
      maxzoom: number;
    };
    expect(tilejson.tiles[0]).toContain(
      "/packages/qaarsut-kullorsuaq/land-relief.pmtiles/{z}/{x}/{y}",
    );
    expect(tilejson.minzoom).toBe(3);
  });

  it("falls back to the network protocol for non-pack URLs", async () => {
    registerPmtilesProtocol();
    handler = addProtocolMock.mock.calls[0]![1] as Handler;

    // No pack bound: any pmtiles URL must go through the network fetch.
    const fetchMock = vi.fn(async () => {
      return new Response("", { status: 404 });
    });
    vi.stubGlobal("fetch", fetchMock);

    const abort = new AbortController();
    await expect(
      handler(
        { url: tileUrl("land-relief.pmtiles", 3, 1, 1) },
        abort,
      ),
    ).rejects.toThrow(/Bad response code/);
    expect(fetchMock).toHaveBeenCalled();
  });

  it("falls back to network after unbind (pack deleted)", async () => {
    registerPmtilesProtocol();
    handler = addProtocolMock.mock.calls[0]![1] as Handler;

    await bindCorridorPackToProtocol(async () => packBlob());
    unbindCorridorPackFromProtocol();

    const fetchMock = vi.fn(async () => new Response("", { status: 404 }));
    vi.stubGlobal("fetch", fetchMock);
    const abort = new AbortController();
    await expect(
      handler(
        { url: tileUrl("ocean-depth.pmtiles", 3, 1, 1) },
        abort,
      ),
    ).rejects.toThrow();
    expect(fetchMock).toHaveBeenCalled();
  });

  it("rejects a bind when a required pack file is missing from OPFS", async () => {
    registerPmtilesProtocol();
    handler = addProtocolMock.mock.calls[0]![1] as Handler;

    await expect(
      bindCorridorPackToProtocol(async () => null),
    ).rejects.toThrow(/missing from OPFS/);

    // Nothing was bound: the tile request still goes to the network.
    const fetchMock = vi.fn(async () => new Response("", { status: 404 }));
    vi.stubGlobal("fetch", fetchMock);
    const abort = new AbortController();
    await expect(
      handler(
        { url: tileUrl("land-relief.pmtiles", 3, 1, 1) },
        abort,
      ),
    ).rejects.toThrow();
  });
});
